### ISSUE TITLE
slush generator events.js throws Syntax error

### ISSUE THREAD

**Issue by monte-hayward** [scalable-react/scalable-react-boilerplate#79]
```
 slush generator-scalable-react
[slush] Using slushfile /Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/slushfile.js
[14:13:14] Starting 'generator-scalable-react:default'...
? What is the name of your project? something
? What is the description? Some Desc
? What is the version of your project? 0.0.1
? What is the author name? Someone
? What is the author email? someone@somewhere.com
? What is the github username? some-one
? Continue? Yes
[14:15:03] [conflict] Keeping
[14:15:03] [conflict] Keeping CHANGELOG.md
[14:15:03] [conflict] Keeping LICENSE
[14:15:03] [conflict] Keeping Procfile
[14:15:03] [conflict] Keeping README.md
[14:15:03] [conflict] Keeping .eslintignore
[14:15:03] [conflict] Keeping .eslintrc.js
[14:15:03] [conflict] Keeping .gitattributes
[14:15:03] [conflict] Keeping .gitignore
[14:15:03] [conflict] Keeping app
[14:15:03] [conflict] Keeping config
[14:15:03] [conflict] Keeping devServer.js
[14:15:03] [conflict] Keeping package.json
[14:15:03] [conflict] Keeping server
[14:15:03] [conflict] Keeping server.js
[14:15:03] [conflict] Keeping webpack.config.babel.js
[14:15:03] [conflict] Keeping webpack.config.prod.js
[14:15:03] [conflict] Keeping yarn.lock
[14:15:03] [conflict] Keeping config/generators
[14:15:03] [conflict] Keeping config/schema
[14:15:03] [conflict] Keeping config/templates
[14:15:03] [conflict] Keeping config/testing
[14:15:03] [conflict] Keeping config/webpack
[14:15:03] [conflict] Keeping app/src
[14:15:03] [conflict] Keeping app/styles
[14:15:03] [conflict] Keeping server/app.js
[14:15:03] [conflict] Keeping server/public
[14:15:03] [conflict] Keeping server/utils
[14:15:03] [conflict] Keeping config/generators/component
[14:15:03] [conflict] Keeping config/generators/container
[14:15:03] [conflict] Keeping config/generators/index.js
[14:15:03] [conflict] Keeping config/generators/page
[14:15:03] [conflict] Keeping config/generators/utils
[14:15:03] [conflict] Keeping config/templates/.index.dev.html
[14:15:03] [conflict] Keeping config/templates/.index.prod.html
[14:15:03] [conflict] Keeping config/schema/schema.json
[14:15:03] [conflict] Keeping config/testing/._mocks__
[14:15:03] [conflict] Keeping config/testing/preprocessor.js
[14:15:03] [conflict] Keeping config/webpack/ignoreAssets.js
[14:15:03] [conflict] Keeping app/src/apolloClient.js
[14:15:03] [conflict] Keeping app/src/components
[14:15:03] [conflict] Keeping app/src/config
[14:15:03] [conflict] Keeping app/src/containers
[14:15:03] [conflict] Keeping app/src/index.js
[14:15:03] [conflict] Keeping app/src/pages
[14:15:03] [conflict] Keeping app/src/reducers.js
[14:15:03] [conflict] Keeping app/src/routes.js
[14:15:03] [conflict] Keeping app/src/store.js
[14:15:03] [conflict] Keeping app/styles/styles.scss
[14:15:03] [conflict] Keeping server/public/0.399358a1fb17e9351bfb.chunk.js
[14:15:03] [conflict] Keeping server/public/1.ccf66c3cbb794c526aa9.chunk.js
[14:15:03] [conflict] Keeping server/public/2.033eb02a5166f88a2098.chunk.js
[14:15:03] [conflict] Keeping server/public/app
[14:15:03] [conflict] Keeping server/public/favicon
[14:15:03] [conflict] Keeping server/public/index.html
[14:15:03] [conflict] Keeping server/public/main.1cf05d39741e4a0b9cec.js
[14:15:03] [conflict] Keeping server/public/main.2fdea5e308f3f75e99aa4fb5b76f7f8d.css
[14:15:03] [conflict] Keeping server/public/main.2fdea5e308f3f75e99aa4fb5b76f7f8d.css.map
[14:15:03] [conflict] Keeping server/public/manifest.json
[14:15:03] [conflict] Keeping server/public/sw.js
[14:15:03] [conflict] Keeping server/public/vendor.ee495b7b65b3a04d912f.js

events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token )
    at template (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/gulp-template/node_modules/lodash/dist/lodash.js:6306:22)
    at Transform._transform (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/gulp-template/index.js:19:31)
    at Transform._read (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/gulp-template/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/gulp-template/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/gulp-template/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/gulp-template/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/gulp-template/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/monte/.node_modules_global/lib/node_modules/slush-generator-scalable-react/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

**Comment by RyanCCollins** [comment]
Hey @monte-hayward, thanks for letting us know.

The slush generator was deprecated a few months ago due to ongoing issues with the gulp-templates, as you can see here.  It was getting difficult to maintain, so it was decided that we would recommend installing from the repository vs using the slush generator.

Let me know if you have any questions about getting setup from the repo.
